apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-depl
spec:
  replicas: 1
  selector: ##what pod to find the pods
    matchLabels:
      app: auth-mongo
  template:
    metadata: ## the label that apply to the pod
      labels:
        app: auth-mongo
    spec: ## spec of the pod
      containers:
        - name: auth-mongo
          image: mongo ##from dockerHub
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-srv
spec:
  selector:
    app: auth-mongo ##what pod to get access to
  ports:
    - name: db
      protocol: TCP
      port: 27017 ##mongo default port
      targetPort: 27017 ##mongo default port
