name: tests-tickets

on:
  pull_request: #when pull request
    paths:
      - "tickets/**" #and any file inside tickets dir change , then do the job

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd  tickets && npm install && npm run test:ci
