name: tests-orders

on:
  pull_request: #when pull request
    paths:
      - "orders/**" #and any file inside orders dir change , then do the job

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
