name: tests-payments

on:
  pull_request: #when pull request
    paths:
      - "payments/**" #and any file inside payments dir change , then do the job

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
